@startuml
[*] --> Заказан
Заказан --> Подтвержден : Подтвердить производство протеза
Подтвержден --> Исследован : Исследовать пациента
Исследован --> Закрыт : Описать невозможность производства протеза
Исследован --> Спроектирован : Спроектировать протез
Спроектирован --> Произведён : Произвести протез
Исследован --> Произведён : Произвести протез по готовому проекту
Произведён --> Установлен : Установить протез
Установлен --> Наблюдается : Поставить пациента на учёт
Наблюдается --> Закрыт : Завершить наблюдение
[*] <-- Закрыт
@enduml
